services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        container_name: wearecheck-transaction-server
        ports:
            - '${APP_PORT:-89988}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:latest'
        container_name: wearecheck-transaction-mysql
        ports:
            - '${FORWARD_DB_PORT:-43344}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/db:/var/lib/mysql'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wearecheck-transaction-phpmyadmin
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: '${DB_PORT}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - '${PMA_PORT:-34332}:80'
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
